# Generated by Django 6.0.1 on 2026-01-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_is_on_vacation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='contact_number',
            field=models.CharField(max_length=10),
        ),
    ]
