# Generated by Django 6.0.1 on 2026-01-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
